language: node_js

node_js:
  - '9'	
  - '10'

branches:
  only:
    - master

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run lint:ci
  - npm run build:prod

